version: '2.4' # using `2.4` instead of `3` as it seems like v3 doesn't support platform.
services:
  frontend:
    platform: linux/amd64
    build: frontend
    ports:
      - 80:80
    depends_on:
      - backend    
  backend:
    platform: linux/amd64
    build: backend



