version: '2.4'
services:
  frontend:
    platform: linux/amd64
    build: 
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    depends_on:
      - backend    
  backend:
    platform: linux/amd64
    build: backend